### ISSUE TITLE
Ionic app running in <root> zone

### ISSUE THREAD

**Issue by paulpatarinski** [opbeat/opbeat-angular#2]
I am trying to use Opbeat in an ionic 1.x application, isOpbeatZone always returns true, unless I do a full page reload (not acceptable in the case of a SPA).

```
ZoneService.prototype.isOpbeatZone = function () {
      return this.zone.name === window.Zone.current.name
}
```

window.Zone.current.name is set to "<root>" in my case. 

Looks like the zone config default is set to "opbeatRootZone".

I am new to opbeat, so I have no idea what zones are/how they are used. 

Is this a bug or user error on my side?

**Comment by hmdhk** [comment]
Hi @paulpatarinski ,

Thanks for reporting the issue and sorry for the slow reply.
Would you please set a breakpoint and send me your stacktrace?

Cheers,
Hamid

**Comment by paulpatarinski** [comment]
To be clear I am not getting any exceptions thrown...Just nothing is getting reported(no requests to /transactions).

That being said here is a call stack from Chrome Tools : 

<img width="910" alt="screen shot 2016-12-09 at 10 31 03 am" src="https://cloud.githubusercontent.com/assets/7964134/21056405/13dbe426-bdfb-11e6-9ef3-1e27b22988cf.png">

I will also try to repro in a code pen & include that

**Comment by hmdhk** [comment]
Thanks for your reply @paulpatarinski ,
We have considered this issue. Unfortunately we still can't support ionic and I can't provide a timeline for it. 

I will make sure that we consider this as a future improvement.

**Comment by paulpatarinski** [comment]
Any thoughts on a workaround? I tried setting the default zone to <root> that seemed to fix the problem of no request being sent, however no XHR or template data is being reported, only the JS stack. Is there any documentation on how the zones work? I can try PR-ing a fix with a better understanding of Zones. Great work... excited to get it working with our app.

**Comment by hmdhk** [comment]
@paulpatarinski ,

Thanks for your encouragement :)
Sure thing! We use [zone.js](http://github.com/angular/zone.js) library to manage zones. 
Also as a work around have you tried manually bootstrapping your angular application.
Generally in order to make the module work correctly the whole application need to be bootstraped under 'opbeatRootZone'.

**Comment by paulpatarinski** [comment]
I was able to narrow down the issue...Seems to be caused by a conflict with rollbar https://rollbar.com
Will submit a different issue for that
